### ISSUE TITLE
Fronos Village registry crashes

### ISSUE THREAD

**Issue by drunksob** [SteveKunG/More-Planets-GC#1]
so I upgraded to this version 1.2.0 from 1.2.0 pre 1. and now pluto is gone the moons around any planets are gone.

**Comment by SteveKunG** [comment]
Are you install 4-Space mod?

**Comment by drunksob** [comment]
4 space is not installed no

**Comment by drunksob** [comment]
reistalled server from scratch a few times with no 4space just gc3.0.8.266 and moreplanets 1.2.0 and keep crashing when generating fronos villages heres the error:
Description: Exception preparing structure feature

java.lang.ClassCastException: net.minecraft.world.gen.structure.StructureVillagePieces$PieceWeight cannot be cast to stevekung.mods.moreplanets.planets.fronos.worldgen.village.StructureFronosVillagePieceWeight
	at stevekung.mods.moreplanets.planets.fronos.worldgen.village.StructureFronosVillagePieces.getStructureVillageWeightedPieceList(StructureFronosVillagePieces.java:32)
	at stevekung.mods.moreplanets.planets.fronos.worldgen.village.StructureFronosVillageStart.<init>(StructureFronosVillageStart.java:22)
	at stevekung.mods.moreplanets.planets.fronos.worldgen.village.MapGenFronosVillage.func_75049_b(MapGenFronosVillage.java:84)
	at net.minecraft.world.gen.structure.MapGenStructure.func_151538_a(MapGenStructure.java:40)
	at net.minecraft.world.gen.MapGenBase.func_151539_a(SourceFile:30)
	at stevekung.mods.moreplanets.planets.fronos.worldgen.ChunkProviderFronos.func_82695_e(ChunkProviderFronos.java:431)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147465_d(World.java:436)
	at stevekung.mods.moreplanets.planets.fronos.worldgen.dungeon.RoomBossFronos.handleTileEntities(RoomBossFronos.java:96)
	at micdoodle8.mods.galacticraft.core.world.gen.dungeon.MapGenDungeon.handleTileEntities(MapGenDungeon.java:426)
	at stevekung.mods.moreplanets.planets.fronos.worldgen.ChunkProviderFronos.func_73153_a(ChunkProviderFronos.java:338)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1045)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at micdoodle8.mods.galacticraft.api.prefab.entity.EntityTieredRocket.func_70071_h_(EntityTieredRocket.java:229)
	at stevekung.mods.moreplanets.planets.fronos.entities.EntityTier7Rocket.func_70071_h_(EntityTier7Rocket.java:80)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at stevekung.mods.moreplanets.planets.fronos.worldgen.village.StructureFronosVillagePieces.getStructureVillageWeightedPieceList(StructureFronosVillagePieces.java:32)
	at stevekung.mods.moreplanets.planets.fronos.worldgen.village.StructureFronosVillageStart.<init>(StructureFronosVillageStart.java:22)
	at stevekung.mods.moreplanets.planets.fronos.worldgen.village.MapGenFronosVillage.func_75049_b(MapGenFronosVillage.java:84)

-- Feature being prepared --
Details:
	Is feature chunk: True
	Chunk location: 1,5
	Chunk pos hash: 21474836481
	Structure type: stevekung.mods.moreplanets.planets.fronos.worldgen.village.MapGenFronosVillage
Stacktrace:
	at net.minecraft.world.gen.structure.MapGenStructure.func_151538_a(MapGenStructure.java:40)
	at net.minecraft.world.gen.MapGenBase.func_151539_a(SourceFile:30)
	at stevekung.mods.moreplanets.planets.fronos.worldgen.ChunkProviderFronos.func_82695_e(ChunkProviderFronos.java:431)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147465_d(World.java:436)
	at stevekung.mods.moreplanets.planets.fronos.worldgen.dungeon.RoomBossFronos.handleTileEntities(RoomBossFronos.java:96)
	at micdoodle8.mods.galacticraft.core.world.gen.dungeon.MapGenDungeon.handleTileEntities(MapGenDungeon.java:426)
	at stevekung.mods.moreplanets.planets.fronos.worldgen.ChunkProviderFronos.func_73153_a(ChunkProviderFronos.java:338)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1045)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at micdoodle8.mods.galacticraft.api.prefab.entity.EntityTieredRocket.func_70071_h_(EntityTieredRocket.java:229)
	at stevekung.mods.moreplanets.planets.fronos.entities.EntityTier7Rocket.func_70071_h_(EntityTier7Rocket.java:80)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: MorePlanet.Tier7Rocket (stevekung.mods.moreplanets.planets.fronos.entities.EntityTier7Rocket)
	Entity ID: 5783
	Entity Name: entity.MorePlanet.Tier7Rocket.name
	Entity's Exact location: -166.50, 87.15, 241.50
	Entity's Block location: World: (-167,87,241), Chunk: (at 9,5,1 in -11,15; contains blocks -176,0,240 to -161,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [GCEntityPlayerMP['DRUNK_SOB'/2147, l='world', x=-166.50, y=87.40, z=241.50]]
	Chunk stats: ServerChunkCache: 1004 Drop: 0
	Level seed: 112358132134
	Level generator: ID 03 - amplified, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-180,64,240), Chunk: (at 12,4,0 in -12,15; contains blocks -192,0,240 to -177,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3302 game time, 3302 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 11786 (now: false), thunder time: 33159 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by nightstalker6669** [comment]
i can confirm this error. i'm getting the same error when i take off from mercury in a tier 7 rocket.

**Comment by SteveKunG** [comment]
OK. Fixed next version. Thanks!

**Comment by drunksob** [comment]
fixed next version as in 1.7.10 mc? or 1.8 mc?

**Comment by SteveKunG** [comment]
in 1.7.10.

**Comment by drunksob** [comment]
sweet u da man Steve

**Comment by SteveKunG** [comment]
OK. 1.2.1 is released. Please test.

**Comment by drunksob** [comment]
This is FIXED!!! XD
